JNG-3176 Add workflows and update .xml files
BlackBeltTechnology/karaf-features-apache-commons pull request #3
Opened 2022-01-21 13:46 UTC by FarkasValentin

2022-01-27 17:15 UTC, robertcsakany requested changes

2022-01-27 17:15 UTC, robertcsakany commented on .flattened-pom.xml
> +<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
This file have to be removed and added to .gitignore

2022-01-27 17:15 UTC, robertcsakany commented on features/.flattened-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file have to be removed and added to .gitignore

2022-01-27 17:15 UTC, robertcsakany commented on kar/.flattened-pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file have to be removed and added to .gitignore

2022-02-03 15:34 UTC, noherczeg approved these changes

2022-02-03 17:04 UTC, merged